version: "3.9"

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:2345:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]

  rabbit:
    image: rabbitmq
    ports:
      - "127.0.0.1:2765:5672"
