version: "3.9"

x-services-common:
  &common
  env_file:
    - .env
  depends_on:
    migrations:
      condition: service_completed_successfully
    postgres:
      condition: service_healthy
    rabbit:
      condition: service_healthy
  restart: unless-stopped


services:

  telegram-receiver:
    <<: *common
    build:
      context: telegram-receiver

  channel-members-tracker:
    <<: *common
    build:
      context: channel-members-tracker

  core:
    <<: *common
    build:
      context: core

  migrations:
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: core
    command: npx prisma migrate deploy

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:2345:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]

  rabbit:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "127.0.0.1:2765:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
